/*
 * This source file was generated by the Gradle 'init' task
 */
package org.aniguessr;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

import com.fasterxml.jackson.databind.ObjectMapper;

import io.javalin.Javalin;

public class App {

    public static void main(String[] args) {

        Map<String, Room> rooms = new ConcurrentHashMap<>();
        Map<String, Player> players = new ConcurrentHashMap<>();
        var objectMapper = new ObjectMapper();

        var app = Javalin.create(config -> {
            config.routes.get("/health", ctx -> {
                ctx.status(200).json(Map.of("status", "running"));
            });

            config.routes.get("/rooms", ctx -> {
                System.out.println(rooms.toString());
            });

            config.routes.ws("/websocket/game", ws -> {
                ws.onConnect(ctx -> {
                    System.out.println("Connected");
                });

                ws.onMessage(ctx ->{
                    var node = objectMapper.readTree(ctx.message());
                    var type = node.get("type").asText();
                    
                    switch(type){
                        case "CREATE_ROOM" -> 
                        {

                        }

                        case "JOIN_ROOM" ->
                        {

                        }

                        case "PLAYER_LIST" ->
                        {

                        }
                    }
                });

                ws.onClose(ctx -> {
                    System.out.println("Disconnected");
                });

            });
        });

        app.start(7070);
    }

    public void broadcast(Room room){
        for(Player x: room.getPlayers()){
            x.getCtx().send("Hello World");
        }
    }
}
