/*
 * This source file was generated by the Gradle 'init' task
 */
package org.aniguessr;

import java.util.Map;

import com.fasterxml.jackson.databind.ObjectMapper;

import io.javalin.Javalin;

public class App {

    public static void main(String[] args) {

        var objectMapper = new ObjectMapper();
        var gameManager = new GameManager();

        var app = Javalin.create(config -> {


            config.routes.get("/health", ctx -> {
                ctx.status(200).json(Map.of("status", "running"));
            });

            config.routes.get("/rooms", ctx -> {
                System.out.println(gameManager.getAllRoomsSnapshot());
            });

            config.routes.ws("/websocket/game", ws -> {
                ws.onConnect(ctx -> {
                    System.out.println("Connected");
                });

                ws.onMessage(ctx ->{
                    var node = objectMapper.readTree(ctx.message());
                    var type = node.get("type").asText();
                    
                    switch(type){
                        case "CREATE_ROOM" -> 
                        {   
                            String code = gameManager.createRoom(node, ctx);
                            ctx.send(code);
                            
                        }

                        case "JOIN_ROOM" ->
                        {
                            gameManager.joinRoom(node, ctx);
                            gameManager.broadcastPlayers(ctx);
                        }

                        case "GUESS" ->
                        {
                            
                        }

                        case "START_GAME" ->
                        {


                        }
                    }
                });

                ws.onClose(ctx -> {
                    System.out.println(ctx.sessionId + " Disconnected: " + ctx.reason());
                    gameManager.leaveRoom(ctx);
                    gameManager.broadcastPlayers(ctx);
                    
                });

            });
        });

        app.start(7070);
    }
}
