/*
 * This source file was generated by the Gradle 'init' task
 */
package org.aniguessr;

import java.util.Map;

import io.javalin.Javalin;

public class App {

    public static void main(String[] args) {
        var app = Javalin.create(config -> {
            config.routes.get("/health", ctx -> {
                ctx.status(200).json(Map.of("status", "running"));
            });

            config.routes.ws("/websocket/game", ws -> {
                ws.onConnect(ctx -> System.out.println("Connected"));
            });
        });

        app.start(7070);
    }
}
